name: SoundFetch Cloud Runner

on: 
  workflow_dispatch:
    inputs:
      song_name:
        description: 'הכנס את שם השיר להורדה'
        required: true
        default: 'יונתן שינפלד דרך חדשה'

jobs:
  run-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yt-dlp

      - name: Run script
        env:
          SONG_NAME: ${{ github.event.inputs.song_name }}
        run: python3 download.py

      - name: Upload downloaded MP3
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-song
          path: song.mp3
          if-no-files-found: ignore
